### ISSUE TITLE
Can't start daemon

### ISSUE THREAD

**Issue by kevingriffin** [mantoni/eslint_d.js#208]
Here's what happens:

```
$ eslint_d start
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '/nix/store/nfy95cadd3siw7f2xr3adaxvcyafl42z-eslint_d-12.2.0/lib/node_modules/eslint_d/node_modules/core_d/lib/daemon.js'
  ]
}
```

```
$ node /nix/store/nfy95cadd3siw7f2xr3adaxvcyafl42z-eslint_d-12.2.0/lib/node_modules/eslint_d/node_modules/core_d/lib/daemon.js
node:internal/validators:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Module.require (node:internal/modules/cjs/loader:998:3)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/nix/store/nfy95cadd3siw7f2xr3adaxvcyafl42z-eslint_d-12.2.0/lib/node_modules/eslint_d/node_modules/core_d/lib/server.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by Slapbox** [comment]
Same issue today, out of the blue. Reinstalling eslint_d/node/rebooting, nothing seems to work.

**Comment by mantoni** [comment]
So node doesn't seem to like the type of an arguments (`ERR_INVALID_ARG_TYPE`). Can you maybe provide some more information about the environment and the node version?

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having the issue, please write here and I'm happy to re-open.
